export interface VocabWord {
  word: string;
  meaning: string;
  synonyms: string[];
  example: string;
  partOfSpeech: string;
  tag: VocabTag;
}

export type VocabTag =
  | 'Emotions'
  | 'Philosophy'
  | 'Language'
  | 'Nature'
  | 'Behaviour'
  | 'Aesthetics'
  | 'Fate & Luck'
  | 'Science';

export const ALL_TAGS: { id: VocabTag; label: string }[] = [
  { id: 'Emotions',    label: 'Emotions' },
  { id: 'Philosophy',  label: 'Philosophy' },
  { id: 'Language',    label: 'Language' },
  { id: 'Nature',      label: 'Nature' },
  { id: 'Behaviour',   label: 'Behaviour' },
  { id: 'Aesthetics',  label: 'Aesthetics' },
  { id: 'Fate & Luck', label: 'Fate & Luck' },
  { id: 'Science',     label: 'Science' },
];

const VOCAB_WORDS: VocabWord[] = [
  // ── Emotions ──
  {
    word: 'Ephemeral',
    meaning: 'Lasting for a very short time.',
    synonyms: ['fleeting', 'transient', 'momentary'],
    example: 'The beauty of cherry blossoms is ephemeral, lasting only a few days.',
    partOfSpeech: 'adjective',
    tag: 'Emotions',
  },
  {
    word: 'Limerence',
    meaning: 'The state of being infatuated or obsessed with another person.',
    synonyms: ['infatuation', 'obsession', 'passion'],
    example: 'His limerence for her made it impossible to concentrate on anything else.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Lachrymose',
    meaning: 'Tearful or given to weeping.',
    synonyms: ['tearful', 'weepy', 'mournful'],
    example: 'The lachrymose movie had the entire audience in tears by the end.',
    partOfSpeech: 'adjective',
    tag: 'Emotions',
  },
  {
    word: 'Ebullient',
    meaning: 'Cheerful and full of energy.',
    synonyms: ['exuberant', 'buoyant', 'effervescent'],
    example: 'Her ebullient personality made her the life of every party.',
    partOfSpeech: 'adjective',
    tag: 'Emotions',
  },
  {
    word: 'Ennui',
    meaning: 'A feeling of listlessness and dissatisfaction arising from boredom.',
    synonyms: ['boredom', 'tedium', 'languor'],
    example: 'An overwhelming ennui settled over her during the long afternoon.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Saudade',
    meaning: 'A deep emotional state of melancholic longing for something absent.',
    synonyms: ['nostalgia', 'longing', 'yearning'],
    example: 'He felt an intense saudade for his childhood home by the sea.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Hiraeth',
    meaning: 'A Welsh concept of longing for a home you cannot return to, or that never existed.',
    synonyms: ['homesickness', 'longing', 'nostalgia'],
    example: 'There was a hiraeth in his eyes whenever he spoke of the old country.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Clinomania',
    meaning: 'An excessive desire to stay in bed.',
    synonyms: ['bed-addiction', 'slugabed-ism'],
    example: 'His clinomania was worst on cold, rainy Monday mornings.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },

  // ── Philosophy ──
  {
    word: 'Sonder',
    meaning: 'The realisation that each passerby has a life as vivid and complex as your own.',
    synonyms: ['awareness', 'realisation'],
    example: 'Standing in the busy station, she felt a wave of sonder wash over her.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Quixotic',
    meaning: 'Exceedingly idealistic; unrealistic and impractical.',
    synonyms: ['idealistic', 'romantic', 'visionary'],
    example: 'His quixotic plan to reform the entire system overnight was met with scepticism.',
    partOfSpeech: 'adjective',
    tag: 'Philosophy',
  },
  {
    word: 'Zeitgeist',
    meaning: 'The defining spirit or mood of a particular period of history.',
    synonyms: ['spirit of the age', 'ethos', 'climate'],
    example: 'The film perfectly captured the zeitgeist of the 1990s.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Eudaimonia',
    meaning: 'A state of happiness resulting from a life of virtue and self-actualisation.',
    synonyms: ['flourishing', 'well-being', 'fulfilment'],
    example: 'Aristotle believed eudaimonia was the highest human good.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Apotheosis',
    meaning: 'The highest point in the development of something; a culmination or climax.',
    synonyms: ['pinnacle', 'zenith', 'acme'],
    example: 'The symphony was the apotheosis of his career as a composer.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Vicissitude',
    meaning: 'A change of circumstances or fortune, typically one that is unwelcome.',
    synonyms: ['fluctuation', 'change', 'upheaval'],
    example: 'Life is full of vicissitudes that test our resilience.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },

  // ── Language & Literature ──
  {
    word: 'Sesquipedalian',
    meaning: 'Given to using long words; characterised by long words.',
    synonyms: ['long-winded', 'verbose', 'polysyllabic'],
    example: 'The professor\'s sesquipedalian lectures sent half the class to sleep.',
    partOfSpeech: 'adjective',
    tag: 'Language',
  },
  {
    word: 'Verisimilitude',
    meaning: 'The appearance of being true or real.',
    synonyms: ['plausibility', 'authenticity', 'realism'],
    example: 'The novel\'s verisimilitude made readers believe the events actually happened.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Soliloquy',
    meaning: 'An act of speaking one\'s thoughts aloud when alone, especially in a play.',
    synonyms: ['monologue', 'speech', 'aside'],
    example: 'Hamlet\'s "To be or not to be" is perhaps the most famous soliloquy in theatre.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Circumlocution',
    meaning: 'The use of many words where fewer would do, especially to avoid saying something directly.',
    synonyms: ['periphrasis', 'verbosity', 'long-windedness'],
    example: 'His circumlocution made it hard to understand what he actually meant.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Tmesis',
    meaning: 'The separation of parts of a compound word by an intervening word.',
    synonyms: ['word-splitting'],
    example: '"Abso-blooming-lutely" is a playful example of tmesis.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Palimpsest',
    meaning: 'A manuscript on which earlier writing has been erased to make room for later writing.',
    synonyms: ['overwritten text', 'layered document'],
    example: 'The city is a palimpsest, each era building on the ruins of the last.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Logolepsy',
    meaning: 'A fascination or obsession with words.',
    synonyms: ['word-love', 'logophilia'],
    example: 'Her logolepsy led her to read the dictionary for fun every evening.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Tergiversation',
    meaning: 'The making of evasive or conflicting statements; equivocation.',
    synonyms: ['evasion', 'equivocation', 'prevarication'],
    example: 'The politician\'s tergiversation frustrated the journalists.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },

  // ── Nature ──
  {
    word: 'Petrichor',
    meaning: 'The pleasant earthy smell produced when rain falls on dry soil.',
    synonyms: ['earth-scent', 'rain-smell'],
    example: 'After weeks of drought, the petrichor that followed the storm was intoxicating.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },
  {
    word: 'Apricity',
    meaning: 'The warmth of the sun in winter.',
    synonyms: ['winter warmth', 'sun-warmth'],
    example: 'She sat on the bench, basking in the apricity of the January afternoon.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },
  {
    word: 'Pluviophile',
    meaning: 'A person who finds joy and peace during rainy days.',
    synonyms: ['rain-lover'],
    example: 'As a pluviophile, she always felt most creative during thunderstorms.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },
  {
    word: 'Susurrus',
    meaning: 'A whispering or rustling sound.',
    synonyms: ['murmur', 'whisper', 'rustle'],
    example: 'The susurrus of the wind through the pines was deeply calming.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },
  {
    word: 'Deflagrate',
    meaning: 'To burn with sudden and sparkling combustion.',
    synonyms: ['combust', 'ignite', 'blaze'],
    example: 'The chemicals deflagrated on contact, producing a spectacular flash.',
    partOfSpeech: 'verb',
    tag: 'Nature',
  },

  // ── Behaviour ──
  {
    word: 'Surreptitious',
    meaning: 'Kept secret, especially because it would not be approved of.',
    synonyms: ['covert', 'stealthy', 'clandestine'],
    example: 'She took a surreptitious glance at her phone during the meeting.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Obsequious',
    meaning: 'Obedient or attentive to an excessive or servile degree.',
    synonyms: ['sycophantic', 'fawning', 'servile'],
    example: 'The obsequious waiter kept refilling glasses that were barely touched.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Recalcitrant',
    meaning: 'Having an obstinately uncooperative attitude.',
    synonyms: ['unruly', 'defiant', 'rebellious'],
    example: 'The recalcitrant child refused to eat anything green.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Abscond',
    meaning: 'Leave hurriedly and secretly, typically to escape from custody or avoid detection.',
    synonyms: ['flee', 'bolt', 'escape'],
    example: 'The accountant absconded with the company funds overnight.',
    partOfSpeech: 'verb',
    tag: 'Behaviour',
  },
  {
    word: 'Sycophant',
    meaning: 'A person who acts obsequiously toward someone important to gain advantage.',
    synonyms: ['flatterer', 'toady', 'yes-man'],
    example: 'The office was full of sycophants eager to praise the new director.',
    partOfSpeech: 'noun',
    tag: 'Behaviour',
  },
  {
    word: 'Nefarious',
    meaning: 'Wicked or criminal.',
    synonyms: ['villainous', 'heinous', 'sinister'],
    example: 'The villain\'s nefarious plot was thwarted at the last moment.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Solivagant',
    meaning: 'A person who wanders alone.',
    synonyms: ['wanderer', 'loner', 'solitary traveller'],
    example: 'The solivagant crossed the desert with nothing but a map and a canteen.',
    partOfSpeech: 'noun',
    tag: 'Behaviour',
  },
  {
    word: 'Pernicious',
    meaning: 'Having a harmful effect, especially in a gradual or subtle way.',
    synonyms: ['destructive', 'damaging', 'deleterious'],
    example: 'The pernicious influence of misinformation on public opinion is alarming.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },

  // ── Aesthetics ──
  {
    word: 'Mellifluous',
    meaning: 'Sweet or musical; pleasant to hear.',
    synonyms: ['dulcet', 'honeyed', 'euphonious'],
    example: 'Her mellifluous voice made even the dullest lecture enjoyable.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },
  {
    word: 'Ineffable',
    meaning: 'Too great or extreme to be expressed or described in words.',
    synonyms: ['indescribable', 'unspeakable', 'inexpressible'],
    example: 'The view from the summit was of an ineffable beauty.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },
  {
    word: 'Pulchritude',
    meaning: 'Beauty (often used in a humorous or literary way).',
    synonyms: ['beauty', 'attractiveness', 'loveliness'],
    example: 'The pulchritude of the sunset left everyone speechless.',
    partOfSpeech: 'noun',
    tag: 'Aesthetics',
  },
  {
    word: 'Callipygian',
    meaning: 'Having well-shaped buttocks.',
    synonyms: ['shapely', 'curvaceous'],
    example: 'The classical statue was noted for its callipygian form.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },
  {
    word: 'Vellichor',
    meaning: 'The strange wistfulness of used bookshops.',
    synonyms: ['book-nostalgia'],
    example: 'The vellichor of the old library made her linger far longer than planned.',
    partOfSpeech: 'noun',
    tag: 'Aesthetics',
  },
  {
    word: 'Munificent',
    meaning: 'Larger or more generous than is usual or necessary.',
    synonyms: ['generous', 'bountiful', 'lavish'],
    example: 'The munificent donation funded the entire new wing of the hospital.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },

  // ── Fate & Luck ──
  {
    word: 'Serendipity',
    meaning: 'The occurrence of events by chance in a happy or beneficial way.',
    synonyms: ['luck', 'fortune', 'providence'],
    example: 'Finding that rare book at the yard sale was pure serendipity.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },
  {
    word: 'Propinquity',
    meaning: 'The state of being close to someone or something; proximity.',
    synonyms: ['nearness', 'closeness', 'adjacency'],
    example: 'Their propinquity in the small office led to a lasting friendship.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },
  {
    word: 'Lagniappe',
    meaning: 'Something given as a bonus or extra gift.',
    synonyms: ['bonus', 'perk', 'gratuity'],
    example: 'The chef sent out a lagniappe of freshly baked bread with our meal.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },

  // ── Emotions (continued) ──
  {
    word: 'Chrysalism',
    meaning: 'The amniotic tranquillity of being indoors during a thunderstorm.',
    synonyms: ['cosiness', 'sheltered calm'],
    example: 'She wrapped herself in a blanket and savoured the chrysalism as rain lashed the windows.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Kenopsia',
    meaning: 'The eerie, forlorn atmosphere of a place that is usually busy but is now abandoned.',
    synonyms: ['desolation', 'emptiness', 'loneliness'],
    example: 'Walking through the school after hours, she felt a creeping kenopsia.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Melancholy',
    meaning: 'A feeling of pensive sadness, typically with no obvious cause.',
    synonyms: ['sadness', 'despondency', 'gloom'],
    example: 'The old photographs filled him with a gentle melancholy.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Euphoria',
    meaning: 'A feeling or state of intense excitement and happiness.',
    synonyms: ['elation', 'ecstasy', 'bliss'],
    example: 'Crossing the finish line, she was flooded with euphoria.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Equanimity',
    meaning: 'Mental calmness and composure, especially in difficult situations.',
    synonyms: ['composure', 'serenity', 'tranquillity'],
    example: 'She faced the diagnosis with remarkable equanimity.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Angst',
    meaning: 'A feeling of deep anxiety or dread, typically an unfocused one.',
    synonyms: ['anxiety', 'dread', 'unease'],
    example: 'Teenage angst permeated every page of her diary.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },
  {
    word: 'Reverie',
    meaning: 'A state of being pleasantly lost in one\'s thoughts; a daydream.',
    synonyms: ['daydream', 'trance', 'musing'],
    example: 'She was lost in reverie, staring out at the rain-soaked garden.',
    partOfSpeech: 'noun',
    tag: 'Emotions',
  },

  // ── Philosophy (continued) ──
  {
    word: 'Solipsism',
    meaning: 'The view that the self is all that can be known to exist.',
    synonyms: ['self-centredness', 'egocentrism'],
    example: 'His philosophical solipsism made genuine connection with others impossible.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Cogito',
    meaning: 'The principle establishing the existence of a being from the fact of its thinking.',
    synonyms: ['self-awareness', 'consciousness'],
    example: 'Descartes\' cogito — "I think, therefore I am" — remains a cornerstone of philosophy.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Absurdism',
    meaning: 'The belief that human beings exist in a purposeless universe.',
    synonyms: ['nihilism', 'existentialism'],
    example: 'Camus explored absurdism through the myth of Sisyphus.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Empiricism',
    meaning: 'The theory that knowledge comes only from sensory experience.',
    synonyms: ['observation', 'pragmatism', 'experientialism'],
    example: 'Locke\'s empiricism rejected innate ideas in favour of learned experience.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Dialectic',
    meaning: 'The art of investigating or discussing the truth of opinions through reasoned argument.',
    synonyms: ['debate', 'reasoning', 'discourse'],
    example: 'The Socratic dialectic challenged students to question every assumption.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Teleology',
    meaning: 'Explanation of phenomena by the purpose they serve rather than by prior causes.',
    synonyms: ['purpose', 'end-goal', 'finalism'],
    example: 'Aristotle\'s teleology held that everything has a natural purpose or telos.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Ontology',
    meaning: 'The branch of metaphysics dealing with the nature of being.',
    synonyms: ['metaphysics', 'being-study'],
    example: 'The ontology of consciousness remains one of philosophy\'s hardest problems.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },
  {
    word: 'Simulacrum',
    meaning: 'An image or representation of someone or something; an unsatisfactory imitation.',
    synonyms: ['copy', 'replica', 'facsimile'],
    example: 'Baudrillard argued that modern society worships the simulacrum over the real.',
    partOfSpeech: 'noun',
    tag: 'Philosophy',
  },

  // ── Language (continued) ──
  {
    word: 'Apophenia',
    meaning: 'The tendency to perceive meaningful connections between unrelated things.',
    synonyms: ['pattern-seeking', 'pareidolia-kin'],
    example: 'His apophenia led him to see conspiracy in every coincidence.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Aphorism',
    meaning: 'A pithy observation that contains a general truth.',
    synonyms: ['maxim', 'adage', 'proverb'],
    example: '"Less is more" is an aphorism beloved by designers and minimalists alike.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Catachresis',
    meaning: 'The use of a word in a way that is not correct, such as using "disinterested" to mean "uninterested".',
    synonyms: ['misuse', 'abuse of language'],
    example: 'Saying "I could care less" is a common catachresis.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Lexicon',
    meaning: 'The vocabulary of a person, language, or branch of knowledge.',
    synonyms: ['vocabulary', 'word-stock', 'glossary'],
    example: 'The internet has added entirely new words to our everyday lexicon.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Litotes',
    meaning: 'Understatement in which an affirmative is expressed by the negative of its contrary.',
    synonyms: ['understatement', 'meiosis'],
    example: '"Not bad at all" is a classic litotes for "very good".',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Synecdoche',
    meaning: 'A figure of speech in which a part is used to represent the whole.',
    synonyms: ['metonymy', 'figure of speech'],
    example: '"All hands on deck" uses synecdoche — hands standing in for sailors.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Euphemism',
    meaning: 'A mild or indirect word substituted for a harsh or blunt one.',
    synonyms: ['polite term', 'softening', 'substitute'],
    example: '"Passed away" is a euphemism for died.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },
  {
    word: 'Paraprosdokian',
    meaning: 'A figure of speech with a surprising or unexpected ending.',
    synonyms: ['surprise ending', 'anticlimax'],
    example: '"I want to die peacefully in my sleep — not screaming like the passengers in his car" is a paraprosdokian.',
    partOfSpeech: 'noun',
    tag: 'Language',
  },

  // ── Nature (continued) ──
  {
    word: 'Virescent',
    meaning: 'Becoming green; greenish.',
    synonyms: ['verdant', 'green', 'lush'],
    example: 'The virescent hillsides signalled the arrival of spring.',
    partOfSpeech: 'adjective',
    tag: 'Nature',
  },
  {
    word: 'Crepuscular',
    meaning: 'Relating to twilight; active at dusk or dawn.',
    synonyms: ['twilight', 'dim', 'dusky'],
    example: 'Deer are crepuscular animals, most active at dawn and dusk.',
    partOfSpeech: 'adjective',
    tag: 'Nature',
  },
  {
    word: 'Sillage',
    meaning: 'The trail of scent left by someone\'s perfume, or the trail left by a ship.',
    synonyms: ['trail', 'wake', 'trace'],
    example: 'Her sillage lingered in the corridor long after she had gone.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },
  {
    word: 'Fulgurite',
    meaning: 'A tube of glassy rock formed when lightning fuses sandy soil.',
    synonyms: ['lightning tube', 'fossilised lightning'],
    example: 'The child held up a fulgurite she\'d found — lightning made solid in the sand.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },
  {
    word: 'Umbra',
    meaning: 'The fully shaded inner region of a shadow cast during an eclipse.',
    synonyms: ['shadow', 'darkness', 'shade'],
    example: 'Totality begins when the moon moves fully into the umbra.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },
  {
    word: 'Sylvan',
    meaning: 'Consisting of or associated with woods; pleasantly rural.',
    synonyms: ['wooded', 'forested', 'pastoral'],
    example: 'They picnicked in a sylvan clearing far from the city noise.',
    partOfSpeech: 'adjective',
    tag: 'Nature',
  },
  {
    word: 'Noctilucent',
    meaning: 'Luminous at night; used to describe rare clouds visible in deep twilight.',
    synonyms: ['night-glowing', 'bioluminescent'],
    example: 'The noctilucent clouds shimmered silver-blue high above the horizon.',
    partOfSpeech: 'adjective',
    tag: 'Nature',
  },
  {
    word: 'Eluvium',
    meaning: 'Rock debris and soil produced by the weathering of rocks in situ.',
    synonyms: ['weathered rock', 'residual soil'],
    example: 'The valley floor was thick with eluvium washed down from the cliffs above.',
    partOfSpeech: 'noun',
    tag: 'Nature',
  },

  // ── Behaviour (continued) ──
  {
    word: 'Loquacious',
    meaning: 'Tending to talk a great deal; talkative.',
    synonyms: ['talkative', 'garrulous', 'voluble'],
    example: 'The loquacious tour guide barely paused for breath throughout the two-hour tour.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Pusillanimous',
    meaning: 'Showing a lack of courage or determination.',
    synonyms: ['cowardly', 'timid', 'faint-hearted'],
    example: 'His pusillanimous response to the crisis disappointed his entire team.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Truculent',
    meaning: 'Eager or quick to argue or fight; aggressively defiant.',
    synonyms: ['belligerent', 'combative', 'aggressive'],
    example: 'The truculent customer argued with every member of staff.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Perspicuous',
    meaning: 'Clearly expressed and easily understood; lucid.',
    synonyms: ['clear', 'lucid', 'transparent'],
    example: 'A perspicuous explanation can save hours of confusion later.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Cavil',
    meaning: 'To make petty or unnecessary objections.',
    synonyms: ['quibble', 'nitpick', 'carp'],
    example: 'He would cavil over every line in the contract, exhausting his colleagues.',
    partOfSpeech: 'verb',
    tag: 'Behaviour',
  },
  {
    word: 'Perfidious',
    meaning: 'Deceitful and untrustworthy.',
    synonyms: ['treacherous', 'disloyal', 'duplicitous'],
    example: 'His perfidious behaviour destroyed the trust of everyone around him.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Wanton',
    meaning: 'Acting or done with a reckless disregard for law or morality.',
    synonyms: ['reckless', 'gratuitous', 'deliberate'],
    example: 'The wanton destruction of the forest for a car park outraged the community.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },
  {
    word: 'Sagacious',
    meaning: 'Having or showing keen mental discernment and good judgement.',
    synonyms: ['wise', 'shrewd', 'astute'],
    example: 'Her sagacious advice had guided the company through many crises.',
    partOfSpeech: 'adjective',
    tag: 'Behaviour',
  },

  // ── Aesthetics (continued) ──
  {
    word: 'Chiaroscuro',
    meaning: 'The treatment of light and shadow in drawing and painting.',
    synonyms: ['light-shadow contrast', 'tonal contrast'],
    example: 'Caravaggio\'s mastery of chiaroscuro gave his figures a dramatic, sculptural quality.',
    partOfSpeech: 'noun',
    tag: 'Aesthetics',
  },
  {
    word: 'Shibui',
    meaning: 'A Japanese concept of subtle, restrained, and unobtrusive beauty.',
    synonyms: ['understated elegance', 'refined simplicity'],
    example: 'The tea ceremony embodied shibui — nothing excessive, nothing missing.',
    partOfSpeech: 'noun',
    tag: 'Aesthetics',
  },
  {
    word: 'Liminal',
    meaning: 'Relating to a transitional or initial stage; on a threshold.',
    synonyms: ['transitional', 'threshold', 'in-between'],
    example: 'The empty airport at 3 a.m. has a distinctly liminal atmosphere.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },
  {
    word: 'Numinous',
    meaning: 'Having a strong religious or spiritual quality; mysterious and awe-inspiring.',
    synonyms: ['sacred', 'divine', 'awe-inspiring'],
    example: 'Standing inside the ancient cathedral, she felt something numinous and vast.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },
  {
    word: 'Diaphanous',
    meaning: 'Light, delicate, and translucent.',
    synonyms: ['translucent', 'gauzy', 'sheer'],
    example: 'Her diaphanous dress caught the light as she moved across the stage.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },
  {
    word: 'Resplendent',
    meaning: 'Attractive and impressive through being richly colourful or sumptuous.',
    synonyms: ['magnificent', 'glorious', 'dazzling'],
    example: 'The ballroom was resplendent with hundreds of candles reflected in gilded mirrors.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },
  {
    word: 'Sfumato',
    meaning: 'A technique of allowing tones and colours to shade gradually into one another.',
    synonyms: ['blending', 'soft-focus', 'gradation'],
    example: 'Leonardo\'s sfumato gave the Mona Lisa her famously mysterious expression.',
    partOfSpeech: 'noun',
    tag: 'Aesthetics',
  },
  {
    word: 'Sublime',
    meaning: 'Of such excellence, grandeur, or beauty as to inspire great admiration or awe.',
    synonyms: ['magnificent', 'transcendent', 'awe-inspiring'],
    example: 'The view of the glacier was nothing short of sublime.',
    partOfSpeech: 'adjective',
    tag: 'Aesthetics',
  },

  // ── Fate & Luck (continued) ──
  {
    word: 'Kismet',
    meaning: 'Destiny; fate.',
    synonyms: ['fate', 'destiny', 'fortune'],
    example: 'They both missed their flights and ended up on the same bench — pure kismet.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },
  {
    word: 'Nemesis',
    meaning: 'The inescapable agent of someone\'s downfall; a long-standing rival.',
    synonyms: ['downfall', 'adversary', 'retribution'],
    example: 'Hubris proved to be the hero\'s nemesis.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },
  {
    word: 'Apotropaic',
    meaning: 'Supposedly having the power to avert evil influences.',
    synonyms: ['protective', 'warding', 'talismanic'],
    example: 'The horseshoe above the door was an apotropaic charm.',
    partOfSpeech: 'adjective',
    tag: 'Fate & Luck',
  },
  {
    word: 'Kairos',
    meaning: 'The right, critical, or opportune moment to act.',
    synonyms: ['opportune moment', 'appointed time', 'turning point'],
    example: 'The general waited for kairos — the precise moment when victory became possible.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },
  {
    word: 'Synchronicity',
    meaning: 'The simultaneous occurrence of events which appear significantly related but have no causal connection.',
    synonyms: ['coincidence', 'meaningful chance', 'acausal connection'],
    example: 'Jung called it synchronicity when he dreamed of a scarab the moment one appeared at his window.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },
  {
    word: 'Portent',
    meaning: 'A sign or warning that something momentous or calamitous is likely to happen.',
    synonyms: ['omen', 'sign', 'augury'],
    example: 'The sudden silence of birds in the forest was a portent of the coming storm.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },
  {
    word: 'Moirai',
    meaning: 'The three Greek goddesses who controlled the fate of every mortal from birth to death.',
    synonyms: ['Fates', 'Parcae', 'destiny-weavers'],
    example: 'Like the Moirai, she seemed to hold the threads of everyone\'s future in her hands.',
    partOfSpeech: 'noun',
    tag: 'Fate & Luck',
  },

  // ── Science ──
  {
    word: 'Defenestration',
    meaning: 'The act of throwing someone out of a window.',
    synonyms: ['ejection', 'expulsion'],
    example: 'The defenestration of Prague is one of history\'s most dramatic political acts.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Perspicacious',
    meaning: 'Having a ready insight into and understanding of things.',
    synonyms: ['astute', 'shrewd', 'perceptive'],
    example: 'A perspicacious detective, she noticed the one clue everyone else had missed.',
    partOfSpeech: 'adjective',
    tag: 'Science',
  },
  {
    word: 'Ubiquitous',
    meaning: 'Present, appearing, or found everywhere.',
    synonyms: ['omnipresent', 'pervasive', 'universal'],
    example: 'Smartphones have become ubiquitous in modern life.',
    partOfSpeech: 'adjective',
    tag: 'Science',
  },
  {
    word: 'Penumbra',
    meaning: 'The partially shaded outer region of the shadow cast by an opaque object.',
    synonyms: ['shadow', 'shade', 'half-shadow'],
    example: 'The moon passed through the penumbra before the total eclipse.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Phosphenes',
    meaning: 'The light patterns you see when you rub your closed eyes.',
    synonyms: ['eye-sparks', 'pressure lights'],
    example: 'He pressed his palms to his eyes and watched the phosphenes dance.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Eigenvalue',
    meaning: 'A value associated with a linear system of equations that represents how a transformation scales space.',
    synonyms: ['characteristic value', 'spectral value'],
    example: 'Google\'s PageRank algorithm is essentially a calculation of the dominant eigenvalue.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Aphelion',
    meaning: 'The point in the orbit of a planet or comet at which it is furthest from the sun.',
    synonyms: ['far point', 'orbital maximum'],
    example: 'Earth reaches its aphelion in early July, when it is about 152 million km from the sun.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Entropy',
    meaning: 'A measure of the disorder or randomness in a closed system.',
    synonyms: ['disorder', 'randomness', 'chaos'],
    example: 'Left unattended, the entropy of any desk will inevitably increase.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Pareidolia',
    meaning: 'The tendency to perceive a specific, often meaningful image in a random or ambiguous pattern.',
    synonyms: ['pattern-recognition', 'apophenia'],
    example: 'Seeing a face in the clouds is a harmless example of pareidolia.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Taxonomy',
    meaning: 'The branch of science concerned with classification, especially of living organisms.',
    synonyms: ['classification', 'categorisation', 'systematics'],
    example: 'Linnaeus\' taxonomy gave scientists a shared language for naming species.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Quasar',
    meaning: 'A massive and extremely remote celestial object that emits exceptionally large amounts of energy.',
    synonyms: ['quasi-stellar object', 'active galactic nucleus'],
    example: 'The quasar blazes with the energy of a trillion suns from the edge of the observable universe.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Osmosis',
    meaning: 'The process by which molecules pass through a semipermeable membrane from a less concentrated solution.',
    synonyms: ['diffusion', 'permeation', 'absorption'],
    example: 'Plant roots absorb water through osmosis.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Catalysis',
    meaning: 'The acceleration of a chemical reaction by a catalyst.',
    synonyms: ['acceleration', 'facilitation', 'activation'],
    example: 'Without catalysis, many industrial chemical reactions would be too slow to be practical.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
  {
    word: 'Parallax',
    meaning: 'The apparent displacement of an object caused by a change in the observer\'s point of view.',
    synonyms: ['apparent shift', 'viewing angle'],
    example: 'Astronomers use stellar parallax to measure the distance to nearby stars.',
    partOfSpeech: 'noun',
    tag: 'Science',
  },
];

export default VOCAB_WORDS;
